// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

package main

import (
	fmt "fmt"
	_ "github.com/cjp2600/protoc-gen-bom/plugin/options"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// user types existing in the system
type UserTypes int32

const (
	UserTypes_pupil   UserTypes = 0
	UserTypes_teacher UserTypes = 1
	UserTypes_admin   UserTypes = 4
)

var UserTypes_name = map[int32]string{
	0: "pupil",
	1: "teacher",
	4: "admin",
}

var UserTypes_value = map[string]int32{
	"pupil":   0,
	"teacher": 1,
	"admin":   4,
}

func (x UserTypes) String() string {
	return proto.EnumName(UserTypes_name, int32(x))
}

func (UserTypes) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{0}
}

// user base response model
type UserResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *User    `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{0}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *UserResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UserResponse) GetData() *User {
	if m != nil {
		return m.Data
	}
	return nil
}

type Role struct {
	Id                   string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string        `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Role                 []*Permission `protobuf:"bytes,3,rep,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Role) Reset()         { *m = Role{} }
func (m *Role) String() string { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()    {}
func (*Role) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{1}
}

func (m *Role) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Role.Unmarshal(m, b)
}
func (m *Role) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Role.Marshal(b, m, deterministic)
}
func (m *Role) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Role.Merge(m, src)
}
func (m *Role) XXX_Size() int {
	return xxx_messageInfo_Role.Size(m)
}
func (m *Role) XXX_DiscardUnknown() {
	xxx_messageInfo_Role.DiscardUnknown(m)
}

var xxx_messageInfo_Role proto.InternalMessageInfo

func (m *Role) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Role) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Role) GetRole() []*Permission {
	if m != nil {
		return m.Role
	}
	return nil
}

type Permission struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Service              string   `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	Create               bool     `protobuf:"varint,4,opt,name=create,proto3" json:"create,omitempty"`
	Read                 bool     `protobuf:"varint,5,opt,name=read,proto3" json:"read,omitempty"`
	Update               bool     `protobuf:"varint,6,opt,name=update,proto3" json:"update,omitempty"`
	Delete               bool     `protobuf:"varint,7,opt,name=delete,proto3" json:"delete,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Permission) Reset()         { *m = Permission{} }
func (m *Permission) String() string { return proto.CompactTextString(m) }
func (*Permission) ProtoMessage()    {}
func (*Permission) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{2}
}

func (m *Permission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Permission.Unmarshal(m, b)
}
func (m *Permission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Permission.Marshal(b, m, deterministic)
}
func (m *Permission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Permission.Merge(m, src)
}
func (m *Permission) XXX_Size() int {
	return xxx_messageInfo_Permission.Size(m)
}
func (m *Permission) XXX_DiscardUnknown() {
	xxx_messageInfo_Permission.DiscardUnknown(m)
}

var xxx_messageInfo_Permission proto.InternalMessageInfo

func (m *Permission) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Permission) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *Permission) GetCreate() bool {
	if m != nil {
		return m.Create
	}
	return false
}

func (m *Permission) GetRead() bool {
	if m != nil {
		return m.Read
	}
	return false
}

func (m *Permission) GetUpdate() bool {
	if m != nil {
		return m.Update
	}
	return false
}

func (m *Permission) GetDelete() bool {
	if m != nil {
		return m.Delete
	}
	return false
}

// user base model
type User struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Active               bool                 `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	FirstName            string               `protobuf:"bytes,3,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string               `protobuf:"bytes,4,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Phone                string               `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	Email                string               `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	Role                 *Role                `protobuf:"bytes,9,opt,name=role,proto3" json:"role,omitempty"`
	EmailConfirm         bool                 `protobuf:"varint,10,opt,name=EmailConfirm,proto3" json:"EmailConfirm,omitempty"`
	Type                 UserTypes            `protobuf:"varint,11,opt,name=type,proto3,enum=main.UserTypes" json:"type,omitempty"`
	Token                *Token               `protobuf:"bytes,12,opt,name=token,proto3" json:"token,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,13,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,14,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	Arguments            map[string]string    `protobuf:"bytes,15,rep,name=arguments,proto3" json:"arguments,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{3}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetRole() *Role {
	if m != nil {
		return m.Role
	}
	return nil
}

func (m *User) GetEmailConfirm() bool {
	if m != nil {
		return m.EmailConfirm
	}
	return false
}

func (m *User) GetType() UserTypes {
	if m != nil {
		return m.Type
	}
	return UserTypes_pupil
}

func (m *User) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *User) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *User) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *User) GetArguments() map[string]string {
	if m != nil {
		return m.Arguments
	}
	return nil
}

type ShortUser struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Active               bool     `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	FirstName            string   `protobuf:"bytes,3,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,4,opt,name=lastName,proto3" json:"lastName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShortUser) Reset()         { *m = ShortUser{} }
func (m *ShortUser) String() string { return proto.CompactTextString(m) }
func (*ShortUser) ProtoMessage()    {}
func (*ShortUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{4}
}

func (m *ShortUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShortUser.Unmarshal(m, b)
}
func (m *ShortUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShortUser.Marshal(b, m, deterministic)
}
func (m *ShortUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShortUser.Merge(m, src)
}
func (m *ShortUser) XXX_Size() int {
	return xxx_messageInfo_ShortUser.Size(m)
}
func (m *ShortUser) XXX_DiscardUnknown() {
	xxx_messageInfo_ShortUser.DiscardUnknown(m)
}

var xxx_messageInfo_ShortUser proto.InternalMessageInfo

func (m *ShortUser) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ShortUser) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *ShortUser) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *ShortUser) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

type Token struct {
	AccessToken          string   `protobuf:"bytes,3,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	RefreshToken         string   `protobuf:"bytes,4,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{5}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *Token) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

type ProviderUsers struct {
	ProviderId           string   `protobuf:"bytes,1,opt,name=providerId,proto3" json:"providerId,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProviderUsers) Reset()         { *m = ProviderUsers{} }
func (m *ProviderUsers) String() string { return proto.CompactTextString(m) }
func (*ProviderUsers) ProtoMessage()    {}
func (*ProviderUsers) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{6}
}

func (m *ProviderUsers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProviderUsers.Unmarshal(m, b)
}
func (m *ProviderUsers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProviderUsers.Marshal(b, m, deterministic)
}
func (m *ProviderUsers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProviderUsers.Merge(m, src)
}
func (m *ProviderUsers) XXX_Size() int {
	return xxx_messageInfo_ProviderUsers.Size(m)
}
func (m *ProviderUsers) XXX_DiscardUnknown() {
	xxx_messageInfo_ProviderUsers.DiscardUnknown(m)
}

var xxx_messageInfo_ProviderUsers proto.InternalMessageInfo

func (m *ProviderUsers) GetProviderId() string {
	if m != nil {
		return m.ProviderId
	}
	return ""
}

func (m *ProviderUsers) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func init() {
	proto.RegisterEnum("main.UserTypes", UserTypes_name, UserTypes_value)
	proto.RegisterType((*UserResponse)(nil), "main.UserResponse")
	proto.RegisterType((*Role)(nil), "main.Role")
	proto.RegisterType((*Permission)(nil), "main.Permission")
	proto.RegisterType((*User)(nil), "main.User")
	proto.RegisterMapType((map[string]string)(nil), "main.User.ArgumentsEntry")
	proto.RegisterType((*ShortUser)(nil), "main.ShortUser")
	proto.RegisterType((*Token)(nil), "main.Token")
	proto.RegisterType((*ProviderUsers)(nil), "main.ProviderUsers")
}

func init() { proto.RegisterFile("test.proto", fileDescriptor_c161fcfdc0c3ff1e) }

var fileDescriptor_c161fcfdc0c3ff1e = []byte{
	// 846 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x54, 0xd1, 0x8e, 0xe3, 0x34,
	0x17, 0xfe, 0xdd, 0x49, 0x3b, 0xcd, 0xe9, 0xcc, 0x6c, 0x65, 0xfd, 0xac, 0xb2, 0xd5, 0x0a, 0xba,
	0x01, 0x89, 0x68, 0xa4, 0x49, 0x4a, 0x91, 0x60, 0x55, 0x71, 0xb3, 0xac, 0x16, 0x69, 0x6f, 0xd0,
	0x2a, 0x3b, 0x80, 0xe0, 0x06, 0xdc, 0xe4, 0x34, 0x35, 0x9b, 0xc4, 0x91, 0xed, 0x14, 0xf5, 0x96,
	0x1b, 0x1e, 0x80, 0x97, 0xe0, 0x12, 0xf1, 0x08, 0x73, 0x31, 0x2f, 0xc0, 0x2b, 0xf0, 0x20, 0xc8,
	0x76, 0x3a, 0xcd, 0x48, 0x68, 0xb9, 0xe3, 0xce, 0xdf, 0x77, 0x3e, 0x7f, 0x3e, 0x3e, 0xe7, 0xd8,
	0x00, 0x1a, 0x95, 0x8e, 0x1b, 0x29, 0xb4, 0xa0, 0x5e, 0xc5, 0x78, 0x3d, 0x5b, 0x15, 0x5c, 0x6f,
	0xdb, 0x75, 0x9c, 0x89, 0x2a, 0xc9, 0x7e, 0x6c, 0x96, 0x9f, 0x2c, 0x16, 0x89, 0x8d, 0x67, 0x57,
	0x05, 0xd6, 0x57, 0x6b, 0x51, 0x25, 0x4d, 0xd9, 0x16, 0xbc, 0x4e, 0x44, 0xa3, 0xb9, 0xa8, 0x55,
	0xb2, 0x16, 0x95, 0x73, 0x98, 0xbd, 0x57, 0x08, 0x51, 0x94, 0xe8, 0xf4, 0xeb, 0x76, 0x93, 0x68,
	0x5e, 0xa1, 0xd2, 0xac, 0x6a, 0x3a, 0xc1, 0x77, 0x3d, 0xf3, 0x42, 0x36, 0xd9, 0x15, 0x66, 0x42,
	0xed, 0x95, 0xc6, 0x0e, 0x16, 0x4c, 0xe3, 0x4f, 0x6c, 0x9f, 0xe8, 0x2d, 0x97, 0xf9, 0xf7, 0x0d,
	0x93, 0x7a, 0x9f, 0x38, 0x4f, 0xd6, 0x70, 0xd5, 0x2d, 0x13, 0xd6, 0xf0, 0x84, 0xd5, 0xb5, 0xd0,
	0xcc, 0x26, 0xe0, 0xbc, 0xc3, 0x1f, 0xe0, 0xec, 0x2b, 0x85, 0x32, 0x45, 0xd5, 0x88, 0x5a, 0x21,
	0x7d, 0x08, 0x23, 0xa5, 0x99, 0x6e, 0x55, 0x40, 0xe6, 0x24, 0x1a, 0xa6, 0x1d, 0xa2, 0x01, 0x9c,
	0x56, 0xa8, 0x14, 0x2b, 0x30, 0x18, 0xcc, 0x49, 0xe4, 0xa7, 0x07, 0x48, 0xdf, 0x05, 0x2f, 0x67,
	0x9a, 0x05, 0x27, 0x73, 0x12, 0x4d, 0x96, 0x10, 0x9b, 0x7a, 0xc4, 0xd6, 0xd3, 0xf2, 0xe1, 0x06,
	0xbc, 0x54, 0x94, 0x48, 0x67, 0x30, 0xe0, 0xb9, 0x75, 0xf5, 0x3f, 0x87, 0x9b, 0xdb, 0xc5, 0x08,
	0xbc, 0x80, 0x44, 0x24, 0x1d, 0xf0, 0x9c, 0x52, 0xf0, 0x6a, 0x56, 0x1d, 0xac, 0xed, 0x9a, 0x7e,
	0x00, 0x9e, 0x14, 0x25, 0x06, 0x27, 0xf3, 0x93, 0x68, 0xb2, 0x9c, 0x3a, 0xdf, 0x57, 0x28, 0x2b,
	0xae, 0x14, 0x17, 0x75, 0x6a, 0xa3, 0xab, 0xf1, 0xcd, 0xed, 0xc2, 0x1b, 0x93, 0x29, 0x09, 0x7f,
	0x23, 0x00, 0xc7, 0xf0, 0x5b, 0x8f, 0x0b, 0xe0, 0x54, 0xa1, 0xdc, 0xf1, 0x0c, 0x6d, 0xd6, 0x7e,
	0x7a, 0x80, 0xe6, 0xfa, 0x99, 0x44, 0xa6, 0x31, 0xf0, 0xe6, 0x24, 0x1a, 0xa7, 0x1d, 0x32, 0x09,
	0x4a, 0x64, 0x79, 0x30, 0xb4, 0xac, 0x5d, 0x1b, 0x6d, 0xdb, 0xe4, 0x46, 0x3b, 0x72, 0x5a, 0x87,
	0x0c, 0x9f, 0x63, 0x89, 0x1a, 0x83, 0x53, 0xc7, 0x3b, 0xd4, 0x4b, 0xf5, 0x0f, 0x0f, 0x3c, 0x53,
	0xa1, 0xb7, 0x26, 0xf9, 0x10, 0x46, 0x2c, 0xd3, 0x7c, 0xe7, 0xaa, 0x32, 0x4e, 0x3b, 0x44, 0x1f,
	0x83, 0xbf, 0xe1, 0x52, 0xe9, 0x2f, 0x4d, 0xc1, 0x5c, 0xfa, 0x47, 0x82, 0xce, 0x60, 0x5c, 0xb2,
	0x2e, 0xe8, 0xd9, 0xe0, 0x1d, 0xa6, 0xff, 0x87, 0x61, 0xb3, 0x15, 0xb5, 0xcb, 0xd7, 0x4f, 0x1d,
	0x30, 0x2c, 0x56, 0x8c, 0x97, 0x36, 0x5b, 0x3f, 0x75, 0xc0, 0x74, 0xd5, 0x56, 0xdf, 0xef, 0x77,
	0xd5, 0xf4, 0xd1, 0xd5, 0x9d, 0x86, 0x70, 0xf6, 0xc2, 0x08, 0x9f, 0x8b, 0x7a, 0xc3, 0x65, 0x15,
	0x80, 0xcd, 0xf1, 0x1e, 0x47, 0xdf, 0x07, 0x4f, 0xef, 0x1b, 0x0c, 0x26, 0x73, 0x12, 0x5d, 0x2c,
	0x1f, 0x1c, 0x27, 0xe3, 0x7a, 0xdf, 0xa0, 0x4a, 0x6d, 0x90, 0x3e, 0x81, 0xa1, 0x16, 0x6f, 0xb0,
	0x0e, 0xce, 0xec, 0x49, 0x13, 0xa7, 0xba, 0x36, 0x54, 0xea, 0x22, 0xf4, 0x29, 0xf8, 0xae, 0x0d,
	0xf9, 0x33, 0x1d, 0x9c, 0x5b, 0xd9, 0x2c, 0x76, 0x53, 0x1d, 0x1f, 0x1e, 0x4d, 0x7c, 0x7d, 0x78,
	0x34, 0xe9, 0x51, 0x6c, 0x76, 0xba, 0xa6, 0x98, 0x9d, 0x17, 0xff, 0xbe, 0xf3, 0x4e, 0x4c, 0x3f,
	0x05, 0x9f, 0xc9, 0xa2, 0xad, 0xb0, 0xd6, 0x2a, 0x78, 0x60, 0x47, 0xf0, 0xd1, 0xf1, 0x02, 0xf1,
	0xb3, 0x43, 0xec, 0x45, 0xad, 0xe5, 0x3e, 0x3d, 0x6a, 0x67, 0x9f, 0xc1, 0xc5, 0xfd, 0x20, 0x9d,
	0xc2, 0xc9, 0x1b, 0xdc, 0xbb, 0x2e, 0xa7, 0x66, 0x69, 0x4a, 0xbe, 0x63, 0x65, 0x7b, 0x98, 0x77,
	0x07, 0x56, 0x83, 0xa7, 0x64, 0xf5, 0xe8, 0xe6, 0x76, 0xf1, 0x8e, 0x9d, 0x11, 0xaf, 0x55, 0x28,
	0x2f, 0xfd, 0xd7, 0x5b, 0x21, 0xb5, 0x39, 0x32, 0xfc, 0x85, 0xc0, 0x11, 0xfd, 0xb7, 0x93, 0xb3,
	0x3a, 0xbb, 0xb9, 0x5d, 0x8c, 0xc7, 0x5d, 0x52, 0xe1, 0x37, 0x30, 0xb4, 0xfd, 0xa1, 0x73, 0x98,
	0xb0, 0x2c, 0x43, 0xa5, 0x2c, 0xec, 0x2c, 0xfb, 0x94, 0x19, 0x13, 0x89, 0x1b, 0x89, 0x6a, 0xeb,
	0x24, 0xce, 0xf8, 0x1e, 0xd7, 0x7b, 0x17, 0x08, 0xe7, 0xaf, 0xa4, 0xd8, 0xf1, 0x1c, 0xa5, 0xb9,
	0xa4, 0xa2, 0x11, 0x40, 0xd3, 0x11, 0x2f, 0x0f, 0xb7, 0xb5, 0x72, 0x18, 0x44, 0x24, 0xed, 0xc5,
	0xe8, 0x1c, 0x46, 0x26, 0xb7, 0x97, 0xb9, 0xab, 0x69, 0x4f, 0xd5, 0xf1, 0xc7, 0x63, 0x2e, 0x63,
	0xf0, 0xef, 0xa6, 0x90, 0xfa, 0x30, 0x6c, 0xda, 0x86, 0x97, 0xd3, 0xff, 0xd1, 0x09, 0x9c, 0x6a,
	0x64, 0xd9, 0x16, 0xe5, 0x94, 0x18, 0x9e, 0xe5, 0x15, 0xaf, 0xa7, 0xde, 0xf2, 0x77, 0x02, 0x13,
	0xb3, 0xe1, 0x75, 0xf7, 0x49, 0x7c, 0x01, 0xf0, 0xdc, 0x8e, 0x98, 0xed, 0x44, 0xef, 0xc7, 0x9b,
	0xd1, 0xde, 0xef, 0xd7, 0xfd, 0xa8, 0x61, 0xf0, 0xf3, 0x9f, 0x7f, 0xfd, 0x3a, 0xa0, 0xe1, 0xb9,
	0xfd, 0x81, 0x77, 0x1f, 0x25, 0x26, 0x1f, 0xb5, 0x22, 0x97, 0xf4, 0x5b, 0x38, 0xff, 0x9a, 0x95,
	0xdc, 0x8c, 0x9c, 0xab, 0x56, 0x7f, 0xf8, 0xff, 0xd1, 0xeb, 0x43, 0xeb, 0xf5, 0x24, 0x7c, 0x7c,
	0xcf, 0x2b, 0xb1, 0xcf, 0x24, 0xd9, 0x75, 0x5e, 0x2b, 0x72, 0xb9, 0x1e, 0xd9, 0xe9, 0xfe, 0xf8,
	0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x39, 0x56, 0x21, 0x1b, 0xaa, 0x06, 0x00, 0x00,
}
