// Code generated by protoc-gen-go. DO NOT EDIT.
// source: plugin/options/bom.proto

package bom

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	descriptor "github.com/gogo/protobuf/protoc-gen-gogo/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type BomFileOptions struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BomFileOptions) Reset()         { *m = BomFileOptions{} }
func (m *BomFileOptions) String() string { return proto.CompactTextString(m) }
func (*BomFileOptions) ProtoMessage()    {}
func (*BomFileOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_0098a2fdbc082952, []int{0}
}

func (m *BomFileOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BomFileOptions.Unmarshal(m, b)
}
func (m *BomFileOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BomFileOptions.Marshal(b, m, deterministic)
}
func (m *BomFileOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BomFileOptions.Merge(m, src)
}
func (m *BomFileOptions) XXX_Size() int {
	return xxx_messageInfo_BomFileOptions.Size(m)
}
func (m *BomFileOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_BomFileOptions.DiscardUnknown(m)
}

var xxx_messageInfo_BomFileOptions proto.InternalMessageInfo

type MongoObject struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MongoObject) Reset()         { *m = MongoObject{} }
func (m *MongoObject) String() string { return proto.CompactTextString(m) }
func (*MongoObject) ProtoMessage()    {}
func (*MongoObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_0098a2fdbc082952, []int{1}
}

func (m *MongoObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MongoObject.Unmarshal(m, b)
}
func (m *MongoObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MongoObject.Marshal(b, m, deterministic)
}
func (m *MongoObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MongoObject.Merge(m, src)
}
func (m *MongoObject) XXX_Size() int {
	return xxx_messageInfo_MongoObject.Size(m)
}
func (m *MongoObject) XXX_DiscardUnknown() {
	xxx_messageInfo_MongoObject.DiscardUnknown(m)
}

var xxx_messageInfo_MongoObject proto.InternalMessageInfo

type BomMessageOptions struct {
	Model                *bool    `protobuf:"varint,1,req,name=model" json:"model,omitempty"`
	Crud                 *bool    `protobuf:"varint,2,opt,name=crud" json:"crud,omitempty"`
	Table                *string  `protobuf:"bytes,3,opt,name=table" json:"table,omitempty"`
	Collection           *string  `protobuf:"bytes,4,opt,name=collection" json:"collection,omitempty"`
	BoundMessage         *string  `protobuf:"bytes,5,opt,name=boundMessage" json:"boundMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BomMessageOptions) Reset()         { *m = BomMessageOptions{} }
func (m *BomMessageOptions) String() string { return proto.CompactTextString(m) }
func (*BomMessageOptions) ProtoMessage()    {}
func (*BomMessageOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_0098a2fdbc082952, []int{2}
}

func (m *BomMessageOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BomMessageOptions.Unmarshal(m, b)
}
func (m *BomMessageOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BomMessageOptions.Marshal(b, m, deterministic)
}
func (m *BomMessageOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BomMessageOptions.Merge(m, src)
}
func (m *BomMessageOptions) XXX_Size() int {
	return xxx_messageInfo_BomMessageOptions.Size(m)
}
func (m *BomMessageOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_BomMessageOptions.DiscardUnknown(m)
}

var xxx_messageInfo_BomMessageOptions proto.InternalMessageInfo

func (m *BomMessageOptions) GetModel() bool {
	if m != nil && m.Model != nil {
		return *m.Model
	}
	return false
}

func (m *BomMessageOptions) GetCrud() bool {
	if m != nil && m.Crud != nil {
		return *m.Crud
	}
	return false
}

func (m *BomMessageOptions) GetTable() string {
	if m != nil && m.Table != nil {
		return *m.Table
	}
	return ""
}

func (m *BomMessageOptions) GetCollection() string {
	if m != nil && m.Collection != nil {
		return *m.Collection
	}
	return ""
}

func (m *BomMessageOptions) GetBoundMessage() string {
	if m != nil && m.BoundMessage != nil {
		return *m.BoundMessage
	}
	return ""
}

type BomFieldOptions struct {
	Tag                  *BomTag  `protobuf:"bytes,1,opt,name=tag" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BomFieldOptions) Reset()         { *m = BomFieldOptions{} }
func (m *BomFieldOptions) String() string { return proto.CompactTextString(m) }
func (*BomFieldOptions) ProtoMessage()    {}
func (*BomFieldOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_0098a2fdbc082952, []int{3}
}

func (m *BomFieldOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BomFieldOptions.Unmarshal(m, b)
}
func (m *BomFieldOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BomFieldOptions.Marshal(b, m, deterministic)
}
func (m *BomFieldOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BomFieldOptions.Merge(m, src)
}
func (m *BomFieldOptions) XXX_Size() int {
	return xxx_messageInfo_BomFieldOptions.Size(m)
}
func (m *BomFieldOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_BomFieldOptions.DiscardUnknown(m)
}

var xxx_messageInfo_BomFieldOptions proto.InternalMessageInfo

func (m *BomFieldOptions) GetTag() *BomTag {
	if m != nil {
		return m.Tag
	}
	return nil
}

type BomTag struct {
	IsID                 *bool    `protobuf:"varint,3,opt,name=isID" json:"isID,omitempty"`
	Skip                 *bool    `protobuf:"varint,4,opt,name=skip" json:"skip,omitempty"`
	MongoObjectId        *bool    `protobuf:"varint,5,opt,name=mongoObjectId" json:"mongoObjectId,omitempty"`
	Update               *bool    `protobuf:"varint,6,opt,name=update" json:"update,omitempty"`
	Additional           *bool    `protobuf:"varint,7,opt,name=additional" json:"additional,omitempty"`
	Validator            *string  `protobuf:"bytes,8,opt,name=validator" json:"validator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BomTag) Reset()         { *m = BomTag{} }
func (m *BomTag) String() string { return proto.CompactTextString(m) }
func (*BomTag) ProtoMessage()    {}
func (*BomTag) Descriptor() ([]byte, []int) {
	return fileDescriptor_0098a2fdbc082952, []int{4}
}

func (m *BomTag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BomTag.Unmarshal(m, b)
}
func (m *BomTag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BomTag.Marshal(b, m, deterministic)
}
func (m *BomTag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BomTag.Merge(m, src)
}
func (m *BomTag) XXX_Size() int {
	return xxx_messageInfo_BomTag.Size(m)
}
func (m *BomTag) XXX_DiscardUnknown() {
	xxx_messageInfo_BomTag.DiscardUnknown(m)
}

var xxx_messageInfo_BomTag proto.InternalMessageInfo

func (m *BomTag) GetIsID() bool {
	if m != nil && m.IsID != nil {
		return *m.IsID
	}
	return false
}

func (m *BomTag) GetSkip() bool {
	if m != nil && m.Skip != nil {
		return *m.Skip
	}
	return false
}

func (m *BomTag) GetMongoObjectId() bool {
	if m != nil && m.MongoObjectId != nil {
		return *m.MongoObjectId
	}
	return false
}

func (m *BomTag) GetUpdate() bool {
	if m != nil && m.Update != nil {
		return *m.Update
	}
	return false
}

func (m *BomTag) GetAdditional() bool {
	if m != nil && m.Additional != nil {
		return *m.Additional
	}
	return false
}

func (m *BomTag) GetValidator() string {
	if m != nil && m.Validator != nil {
		return *m.Validator
	}
	return ""
}

type AutoServerOptions struct {
	Autogen              *bool    `protobuf:"varint,1,opt,name=autogen" json:"autogen,omitempty"`
	TxnMiddleware        *bool    `protobuf:"varint,2,opt,name=txn_middleware,json=txnMiddleware" json:"txn_middleware,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AutoServerOptions) Reset()         { *m = AutoServerOptions{} }
func (m *AutoServerOptions) String() string { return proto.CompactTextString(m) }
func (*AutoServerOptions) ProtoMessage()    {}
func (*AutoServerOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_0098a2fdbc082952, []int{5}
}

func (m *AutoServerOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AutoServerOptions.Unmarshal(m, b)
}
func (m *AutoServerOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AutoServerOptions.Marshal(b, m, deterministic)
}
func (m *AutoServerOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AutoServerOptions.Merge(m, src)
}
func (m *AutoServerOptions) XXX_Size() int {
	return xxx_messageInfo_AutoServerOptions.Size(m)
}
func (m *AutoServerOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_AutoServerOptions.DiscardUnknown(m)
}

var xxx_messageInfo_AutoServerOptions proto.InternalMessageInfo

func (m *AutoServerOptions) GetAutogen() bool {
	if m != nil && m.Autogen != nil {
		return *m.Autogen
	}
	return false
}

func (m *AutoServerOptions) GetTxnMiddleware() bool {
	if m != nil && m.TxnMiddleware != nil {
		return *m.TxnMiddleware
	}
	return false
}

type MethodOptions struct {
	ObjectType           *string  `protobuf:"bytes,1,opt,name=object_type,json=objectType" json:"object_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MethodOptions) Reset()         { *m = MethodOptions{} }
func (m *MethodOptions) String() string { return proto.CompactTextString(m) }
func (*MethodOptions) ProtoMessage()    {}
func (*MethodOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_0098a2fdbc082952, []int{6}
}

func (m *MethodOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MethodOptions.Unmarshal(m, b)
}
func (m *MethodOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MethodOptions.Marshal(b, m, deterministic)
}
func (m *MethodOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MethodOptions.Merge(m, src)
}
func (m *MethodOptions) XXX_Size() int {
	return xxx_messageInfo_MethodOptions.Size(m)
}
func (m *MethodOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_MethodOptions.DiscardUnknown(m)
}

var xxx_messageInfo_MethodOptions proto.InternalMessageInfo

func (m *MethodOptions) GetObjectType() string {
	if m != nil && m.ObjectType != nil {
		return *m.ObjectType
	}
	return ""
}

var E_FileOpts = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*BomFileOptions)(nil),
	Field:         99432,
	Name:          "bom.file_opts",
	Tag:           "bytes,99432,opt,name=file_opts",
	Filename:      "plugin/options/bom.proto",
}

var E_Opts = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*BomMessageOptions)(nil),
	Field:         99432,
	Name:          "bom.opts",
	Tag:           "bytes,99432,opt,name=opts",
	Filename:      "plugin/options/bom.proto",
}

var E_Field = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*BomFieldOptions)(nil),
	Field:         99432,
	Name:          "bom.field",
	Tag:           "bytes,99432,opt,name=field",
	Filename:      "plugin/options/bom.proto",
}

var E_Server = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.ServiceOptions)(nil),
	ExtensionType: (*AutoServerOptions)(nil),
	Field:         99432,
	Name:          "bom.server",
	Tag:           "bytes,99432,opt,name=server",
	Filename:      "plugin/options/bom.proto",
}

var E_Method = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*MethodOptions)(nil),
	Field:         99432,
	Name:          "bom.method",
	Tag:           "bytes,99432,opt,name=method",
	Filename:      "plugin/options/bom.proto",
}

func init() {
	proto.RegisterType((*BomFileOptions)(nil), "bom.BomFileOptions")
	proto.RegisterType((*MongoObject)(nil), "bom.MongoObject")
	proto.RegisterType((*BomMessageOptions)(nil), "bom.BomMessageOptions")
	proto.RegisterType((*BomFieldOptions)(nil), "bom.BomFieldOptions")
	proto.RegisterType((*BomTag)(nil), "bom.BomTag")
	proto.RegisterType((*AutoServerOptions)(nil), "bom.AutoServerOptions")
	proto.RegisterType((*MethodOptions)(nil), "bom.MethodOptions")
	proto.RegisterExtension(E_FileOpts)
	proto.RegisterExtension(E_Opts)
	proto.RegisterExtension(E_Field)
	proto.RegisterExtension(E_Server)
	proto.RegisterExtension(E_Method)
}

func init() { proto.RegisterFile("plugin/options/bom.proto", fileDescriptor_0098a2fdbc082952) }

var fileDescriptor_0098a2fdbc082952 = []byte{
	// 521 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xdb, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0xe5, 0xb6, 0x71, 0x9d, 0x09, 0x29, 0x74, 0xa9, 0xaa, 0x15, 0xea, 0x21, 0xb2, 0x40,
	0xca, 0x55, 0x52, 0x71, 0x99, 0x3b, 0x22, 0x84, 0x54, 0x41, 0x54, 0x58, 0x72, 0x1f, 0xad, 0xbd,
	0x1b, 0xb3, 0xb0, 0xf6, 0x58, 0xf6, 0xba, 0xb4, 0x6f, 0xc0, 0x1b, 0xf0, 0x12, 0x3c, 0x18, 0x8f,
	0x81, 0x3c, 0x8e, 0x73, 0x50, 0xc3, 0xdd, 0xce, 0x3f, 0xa3, 0x6f, 0xff, 0x39, 0x00, 0xcf, 0x6d,
	0x95, 0x98, 0x6c, 0x8c, 0xb9, 0x33, 0x98, 0x95, 0xe3, 0x08, 0xd3, 0x51, 0x5e, 0xa0, 0x43, 0x76,
	0x18, 0x61, 0xfa, 0x6a, 0x90, 0x20, 0x26, 0x56, 0x8f, 0x49, 0x8a, 0xaa, 0xe5, 0x58, 0xe9, 0x32,
	0x2e, 0x4c, 0xee, 0xb0, 0x68, 0xca, 0xc2, 0x17, 0x70, 0x32, 0xc5, 0xf4, 0x83, 0xb1, 0xfa, 0xae,
	0x41, 0x84, 0x7d, 0xe8, 0xcd, 0x30, 0x4b, 0xf0, 0x2e, 0xfa, 0xae, 0x63, 0x17, 0xfe, 0xf6, 0xe0,
	0x74, 0x8a, 0xe9, 0x4c, 0x97, 0xa5, 0x4c, 0xda, 0x22, 0x76, 0x06, 0x9d, 0x14, 0x95, 0xb6, 0xdc,
	0x1b, 0x1c, 0x0c, 0x03, 0xd1, 0x04, 0x8c, 0xc1, 0x51, 0x5c, 0x54, 0x8a, 0x1f, 0x0c, 0xbc, 0x61,
	0x20, 0xe8, 0x5d, 0x57, 0x3a, 0x19, 0x59, 0xcd, 0x0f, 0x07, 0xde, 0xb0, 0x2b, 0x9a, 0x80, 0x5d,
	0x01, 0xc4, 0x68, 0xad, 0x8e, 0x6b, 0x1c, 0x3f, 0xa2, 0xd4, 0x96, 0xc2, 0x42, 0x78, 0x16, 0x61,
	0x95, 0xa9, 0xd5, 0xb7, 0xbc, 0x43, 0x15, 0x3b, 0x5a, 0x78, 0x03, 0xcf, 0xc9, 0xba, 0xb6, 0xaa,
	0xb5, 0x75, 0x09, 0x87, 0x4e, 0x26, 0xdc, 0x1b, 0x78, 0xc3, 0xde, 0xdb, 0xde, 0xa8, 0x9e, 0xc6,
	0x14, 0xd3, 0xb9, 0x4c, 0x44, 0xad, 0x87, 0x7f, 0x3c, 0xf0, 0x9b, 0xb8, 0xb6, 0x6a, 0xca, 0xdb,
	0xf7, 0xe4, 0x2a, 0x10, 0xf4, 0xae, 0xb5, 0xf2, 0x87, 0xc9, 0xc9, 0x4e, 0x20, 0xe8, 0xcd, 0x5e,
	0x43, 0x3f, 0xdd, 0x4c, 0xe3, 0x56, 0x91, 0x93, 0x40, 0xec, 0x8a, 0xec, 0x1c, 0xfc, 0x2a, 0x57,
	0xd2, 0x69, 0xee, 0x53, 0x7a, 0x15, 0xd5, 0x6d, 0x4a, 0xa5, 0x4c, 0x6d, 0x4e, 0x5a, 0x7e, 0x4c,
	0xb9, 0x2d, 0x85, 0x5d, 0x40, 0xf7, 0x5e, 0x5a, 0xa3, 0xa4, 0xc3, 0x82, 0x07, 0xd4, 0xe3, 0x46,
	0x08, 0xe7, 0x70, 0xfa, 0xae, 0x72, 0xf8, 0x55, 0x17, 0xf7, 0xba, 0x68, 0x5b, 0xe4, 0x70, 0x2c,
	0x2b, 0x87, 0x89, 0xce, 0xa8, 0xcd, 0x40, 0xb4, 0x21, 0x7b, 0x03, 0x27, 0xee, 0x21, 0x5b, 0xa4,
	0x46, 0x29, 0xab, 0x7f, 0xca, 0x42, 0xaf, 0xf6, 0xd0, 0x77, 0x0f, 0xd9, 0x6c, 0x2d, 0x86, 0x37,
	0xd0, 0x9f, 0x69, 0xf7, 0x0d, 0xd7, 0x43, 0xbb, 0x86, 0x1e, 0x52, 0x23, 0x0b, 0xf7, 0x98, 0x6b,
	0xa2, 0x76, 0x05, 0x34, 0xd2, 0xfc, 0x31, 0xd7, 0x93, 0xcf, 0xd0, 0x5d, 0x1a, 0xab, 0x17, 0x98,
	0xbb, 0x92, 0x5d, 0x8c, 0x9a, 0x9b, 0x1a, 0xb5, 0x37, 0x35, 0xda, 0x3a, 0x1e, 0xfe, 0xf7, 0x97,
	0x4f, 0xb3, 0x7f, 0xd9, 0xce, 0x7e, 0x2b, 0x29, 0x82, 0x65, 0x13, 0x94, 0x93, 0x19, 0x1c, 0x11,
	0xec, 0xfa, 0x09, 0x6c, 0xf7, 0xce, 0xd6, 0xbc, 0xf3, 0x96, 0xb7, 0x9b, 0x17, 0x84, 0x99, 0x7c,
	0x84, 0xce, 0xb2, 0x3e, 0x03, 0x76, 0xb9, 0xc7, 0xdc, 0xe6, 0x3c, 0xd6, 0xb4, 0xb3, 0x8d, 0xbb,
	0x4d, 0x56, 0x34, 0x8c, 0xc9, 0x17, 0xf0, 0x4b, 0x9a, 0xf8, 0x1e, 0x77, 0xf5, 0x2a, 0x4c, 0xfc,
	0x1f, 0x77, 0x4f, 0x76, 0x25, 0x56, 0xa0, 0xc9, 0x27, 0xf0, 0x53, 0x1a, 0x39, 0xbb, 0xda, 0xd3,
	0xf0, 0xd6, 0x2e, 0xd6, 0x44, 0x46, 0xc4, 0x9d, 0x9c, 0x58, 0x31, 0xfe, 0x05, 0x00, 0x00, 0xff,
	0xff, 0xcc, 0xf9, 0xce, 0xc8, 0xf4, 0x03, 0x00, 0x00,
}
